spring:
    application:
        name: schema-registry-demo-service

kafka:
    bootstrap-servers: pkc-lzvrd.us-west4.gcp.confluent.cloud:9092
    schema.registry.url: https://psrc-x77pq.us-central1.gcp.confluent.cloud
    cluster.key: BWPFCCDAZNMD2WIX
    cluster.secret: cLW395ul5ci7bXUkJXjnW8cwMpJICLtlMC+eAflxPgwcel04YEVYUakfg81i5wgQ
    schema.registry.key: 5FJI3WEEOPWJKBLC
    schema.registry.secret: NTbRdm+EFi6WvuvBPA16PJ4pE+yPeR2F2MuyimojgOem+pJABgsymbknFjjwUhR0

server:
    port: 9001

kafkademo:
    outboundTopic: "demo_topic2"
